### ISSUE TITLE
can't launch SCII after I compile the source.

### ISSUE THREAD

**Issue by K85** [ocraft/ocraft-s2client#48]
The program runs very good in my IDEA.
However, after I compile the project into executable jar.
Then OCraft can't launch SCII.

Message: No configuration setting found for key 'ocraft.bot'
StackTrace:
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
        at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:149)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
        at com.typesafe.config.impl.SimpleConfig.getBoolean(SimpleConfig.java:218)
        at com.github.ocraft.s2client.bot.setting.ProcessSettings.<init>(ProcessSettings.java:42)
        at com.github.ocraft.s2client.bot.S2Coordinator$Builder.<init>(S2Coordinator.java:154)
        at com.github.ocraft.s2client.bot.S2Coordinator$Builder.<init>(S2Coordinator.java:149)
        at com.github.ocraft.s2client.bot.S2Coordinator.setup(S2Coordinator.java:145)
        at com.sakurawald.ui.controller.AppController.lambda$button_launch_onAction$2(AppController.java:117)
        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by ocraft** [comment]
It means that you don't have all of the required dependencies on the classpath. There is an example of how to configure maven to build a jar with required dependencies <https://github.com/ocraft/ocraft-s2client/blob/master/ocraft-s2client-sample/pom.xml>. The final result should look something like this <https://github.com/Cryptyc/Sc2LadderServer/files/2300666/Ocraft.zip>.

**Comment by K85** [comment]
> It means that you don't have all of the required dependencies on the classpath. There is an example of how to configure maven to build a jar with required dependencies https://github.com/ocraft/ocraft-s2client/blob/master/ocraft-s2client-sample/pom.xml. The final result should look something like this https://github.com/Cryptyc/Sc2LadderServer/files/2300666/Ocraft.zip.

thanks，I will try it.
since I have found some ways from StackOverFlow and Google, but helpless.

**Comment by ocraft** [comment]
The fastest way to get help is to ask questions on the dedicated #java channel on the discord server https://discordapp.com/invite/Emm5Ztz

**Comment by K85** [comment]
Great. It works when I use maven build plugins.
